networks:
  toybox.net:
    driver: bridge

services:
  # Base de données
  # ATTENTION : Ton image est Postgres mais tes scripts et ton PHP utilisent MySQL/PDO
  # Je repasse en MySQL pour être cohérent avec ton Repository.php
  db:
    image: "mysql:8.0"
    restart: always
    env_file: ./backend/.env
    # Pas d'exposition de port 3306 nécessaire sur Dockétu (sécurité + conflits)
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - toybox.net

  # Backend (PHP)
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "18082:80" # CHANGE ICI : Utilise ton port attribué (ex: 18082)
    volumes:
      - ./backend:/var/php
    working_dir: /var/php
    depends_on:
      - db
    networks:
      - toybox.net
    command: "php -S 0.0.0.0:80 -t /var/php/public"
    restart: unless-stopped

  # Frontend (Vue.js)
  frontend:
    build: ./frontend
    ports:
      - "15173:5173" # CHANGE ICI : Utilise ton port attribué (ex: 15173)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - toybox.net

  # Adminer (Outil de gestion DB)
  adminer:
    image: adminer
    ports:
      - "18081:8080" # CHANGE ICI : Utilise un port attribué
    networks:
      - toybox.net