networks:
  toybox.net:
    driver: bridge

services:
  # Base de données (MySQL)
  db:
    image: "postgres:latest"
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - toybox.net

  # Backend (PHP + Apache/Nginx)
  backend:
    build: ./backend
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/php
    working_dir: /var/php
    depends_on:
      - db
    networks:
      - toybox.net
    command: "php -S 0.0.0.0:80 -t /var/php/public"
    restart: unless-stopped

  # Frontend (Vue.js)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Port par défaut de Vite/Vue
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - toybox.net

  #adminer
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - toybox.net
