name: Docker Stack Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build et Lancement de la stack
        run: docker compose up -d --build

      - name: Vérification du statut des conteneurs
        run: |
          docker ps
          # On attend quelques secondes pour laisser les services démarrer
          sleep 15 

      - name: Test de réponse du Backend (PHP)
        run: |
          curl --fail http://localhost:8080 || exit 1

      - name: Test de réponse du Frontend (Vue)
        run: |
          curl --fail http://localhost:5173 || exit 1

      - name: Vérification des logs en cas d'échec
        if: failure()
        run: docker compose logs

      - name: Arrêt de la stack
        run: docker compose down